### PR TITLE
Handle race condition of state and code verifier

### LINKED ISSUE #67: "State doesn't match" race condition
We started running into occasional Auth0 failures with "State doesn't match". After a day of banging my head against the wall, I think I have a pretty good idea of what's going on:

https://stackoverflow.com/questions/65493296/authorization-code-flow-concurrent-requests-from-multiple-tabs

If a user simultaneously loads multiple pages while unauthenticated, the result is a race condition:

1. Tab 1 updates `state` and redirects to OAuth
2. Tab 2 updates `state` and redirects to OAuth
   - Overwriting Tab 1 `state`
3. Tab 1 callback fails due to state mismatch
4. Tab 2 callback succeeds

This is pretty common when reopening a closed browser, for example.

### PR DESCRIPTION
**Pull request by sergiodxa**
Fix #67 

When triggering multiple times the OAuth2 flow, each redirect to the authorization URL sets the same cookie with the `state` and `codeVerifier` values. This can cause a race condition where only the last one will work as the previous states and code verifiers will be overwritten by the last Set-Cookie header.

This PR implements a StateStore class that's used internally to keep track of multiple states and code verifiers.

The way it works is that every redirect to the authorization URL will now set a different cookie name, using the provided cookie name (or `oauth2`) as the prefix and appending a UUID (e.g. `oauth2:b450faeb-1f67-461e-bf4d-004b6f0a6e55` or `custom-name:b450faeb-1f67-461e-bf4d-004b6f0a6e55`).

Then when the user is back on the application, the StateStore can read all of these cookies to get every state and code verifier, if the state in the URL matches one of the stored ones, it will then use the associated code verifier to get the tokens from the identity provider.

Because each state and code verifier is stored in a separate cookie, each one can expire individually, which allows using short max age of the cookies (the default is 5 minutes but it could probably be reduced to one or two safely).

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -80,44 +81,42 @@ export class OAuth2Strategy<User> extends Strategy<
...
+
+		if (!codeVerifier) {
 			throw new ReferenceError("Missing code verifier on cookie.");
 		}
 
 		debug("Validating authorization code");
 		let tokens = await this.validateAuthorizationCode(
 			code,
-			params.get("codeVerifier") as string, // We checked above this is defined
+			codeVerifier, // We checked above this is defined
```
Comment (reichhartd) [inline src/index.ts:119]:
```suggestion
			codeVerifier,
```
